SRC			= ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_strlen.c ft_strchr.c ft_strrchr.c ft_strnstr.c ft_strncmp.c ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c ft_calloc.c ft_strdup.c
NAME 		= libft.a
OBJ 		= $(SRC:.c=.o)
INCLUDES 	= ./
CC 			= clang
CFLAGS 		= -Werror -Wall -Wextra

all: $(NAME)

	$(NAME): $(SRC)
		$(CC) $(CFLAGS) -c $^
		ar rc $(NAME) $(OBJ)
		ranlib $(NAME)

clean:
	/bin/rm -f $(OBJ)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all

norme:
	norminette $(SRC)
